<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>icon.ico</ApplicationIcon>

	  <ApplicationTitle>Museum Space</ApplicationTitle>
	  <AssemblyName>MuseumSpace</AssemblyName>
	  <Product>Museum Space</Product>
	  
	  <Version>1.0.0</Version>
	  <AssemblyVersion>1.0.0.0</AssemblyVersion>
	  <FileVersion>1.0.0.0</FileVersion>
	  
  </PropertyGroup>

  <ItemGroup>
    <None Remove="AppSettings.json" />
    <None Remove="Resources\logo.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="AppSettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
    <PackageReference Include="HandyControl" Version="3.5.1" />
    <PackageReference Include="LibVLCSharp" Version="3.10.0" />
    <PackageReference Include="LibVLCSharp.WPF" Version="3.10.0" />
    <PackageReference Include="MahApps.Metro.IconPacks" Version="6.2.1" />
    <PackageReference Include="Markdig" Version="1.2.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4022.49" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\logo.png" />
  </ItemGroup>

	<Target Name="CleanupLibVLC" AfterTargets="Publish">
		<ItemGroup>
			<!-- Удаляем win-arm64 целиком -->
			<LibVLCFoldersToRemove Include="$(PublishDir)libvlc\win-arm64" />

			<!-- Очистка win-x64 -->
			<LibVLCFoldersToRemove Include="
            $(PublishDir)libvlc\win-x64\hrtfs;
            $(PublishDir)libvlc\win-x64\plugins\access_output;
            $(PublishDir)libvlc\win-x64\plugins\audio_mixer;
            $(PublishDir)libvlc\win-x64\plugins\d3d9;
            $(PublishDir)libvlc\win-x64\plugins\d3d11;
            $(PublishDir)libvlc\win-x64\plugins\gui;
            $(PublishDir)libvlc\win-x64\plugins\keystore;
            $(PublishDir)libvlc\win-x64\plugins\logger;
            $(PublishDir)libvlc\win-x64\plugins\lua;
            $(PublishDir)libvlc\win-x64\plugins\meta_engine;
            $(PublishDir)libvlc\win-x64\plugins\misc;
            $(PublishDir)libvlc\win-x64\plugins\mux;
            $(PublishDir)libvlc\win-x64\plugins\packetizer;
            $(PublishDir)libvlc\win-x64\plugins\services_discovery;
            $(PublishDir)libvlc\win-x64\plugins\spu;
            $(PublishDir)libvlc\win-x64\plugins\stream_extractor;
            $(PublishDir)libvlc\win-x64\plugins\stream_out;
            $(PublishDir)libvlc\win-x64\plugins\text_renderer;
            $(PublishDir)libvlc\win-x64\plugins\video_chroma;
            $(PublishDir)libvlc\win-x64\plugins\video_splitter;
            $(PublishDir)libvlc\win-x64\plugins\visualization" />

			<!-- Очистка win-x86 -->
			<LibVLCFoldersToRemove Include="
            $(PublishDir)libvlc\win-x86\hrtfs;
            $(PublishDir)libvlc\win-x86\plugins\access_output;
            $(PublishDir)libvlc\win-x86\plugins\audio_mixer;
            $(PublishDir)libvlc\win-x86\plugins\d3d9;
            $(PublishDir)libvlc\win-x86\plugins\d3d11;
            $(PublishDir)libvlc\win-x86\plugins\gui;
            $(PublishDir)libvlc\win-x86\plugins\keystore;
            $(PublishDir)libvlc\win-x86\plugins\logger;
            $(PublishDir)libvlc\win-x86\plugins\lua;
            $(PublishDir)libvlc\win-x86\plugins\meta_engine;
            $(PublishDir)libvlc\win-x86\plugins\misc;
            $(PublishDir)libvlc\win-x86\plugins\mux;
            $(PublishDir)libvlc\win-x86\plugins\packetizer;
            $(PublishDir)libvlc\win-x86\plugins\services_discovery;
            $(PublishDir)libvlc\win-x86\plugins\spu;
            $(PublishDir)libvlc\win-x86\plugins\stream_extractor;
            $(PublishDir)libvlc\win-x86\plugins\stream_out;
            $(PublishDir)libvlc\win-x86\plugins\text_renderer;
            $(PublishDir)libvlc\win-x86\plugins\video_chroma;
            $(PublishDir)libvlc\win-x86\plugins\video_splitter;
            $(PublishDir)libvlc\win-x86\plugins\visualization" />
		</ItemGroup>

		<RemoveDir Directories="@(LibVLCFoldersToRemove)" />

		<Message Text="LibVLC cleanup completed." Importance="high" />
	</Target>

</Project>
