<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	  
	  <Version>1.0.0</Version>
	  <AssemblyVersion>1.0.0.0</AssemblyVersion>
	  <FileVersion>1.0.0.0</FileVersion>
	
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.25" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.25" />
    <PackageReference Include="QuestPDF" Version="2026.7.2" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\system\UserGuide.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Update="Tools\ffmpeg\linux\ffmpeg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tools\ffmpeg\linux\ffprobe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tools\ffmpeg\win\ffmpeg.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tools\ffmpeg\win\ffprobe.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <!-- Не копировать пользовательские файлы при публикации -->
  <ItemGroup>
  	<Content Remove="wwwroot\documents\**\*" />
  	<Content Remove="wwwroot\exhibits\**\*" />
  	<Content Remove="wwwroot\media\**\*" />
  	<Content Remove="wwwroot\departments\**\*" />
  </ItemGroup>
     
  <!-- Создать пустые папки при публикации -->
  <Target Name="CreateEmptyWwwrootFolders" AfterTargets="Publish">
  	<MakeDir Directories="$(PublishDir)wwwroot\documents;
                           $(PublishDir)wwwroot\exhibits;
                           $(PublishDir)wwwroot\media;
                           $(PublishDir)wwwroot\departments" />
  </Target>
</Project>
